<html>
  <head>
    <title>Code Review :: </title>
    <style type="text/css">
    .body{background-color:White;}
    .summary{width:100%;font-weight:bold;background-color:White;border: thin solid #808000;color:#FAFCFE}
    .outer{font-weight:normal;color:#6D5757;background-color:#FFDFBF}
    .inner{font-weight:normal;color:black;}
    .reviewTable{border: thin solid #C0C0C0; width:100%}
    .headerRow{color:white;background-color: #800000;font-weight:bold;text-align: center}
    .reviewRow{background-color:#FFDFBF;color:black;}
    .rAligned{text-align:right;}
    .data{visibility:hidden}
  </style>
  </head>
  <body class="body">
    <div class="summary">
      <table>
        <tr>
          <td colspan="3" class="headerRow">Review Summary</td>
        </tr>
        <tr class="outer">
          <td>Project Name : <label class="inner" /></td>
          <td>Reviewed By : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Project Code : <label class="inner" /></td>
          <td>Reviewed Date : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Name : <label class="inner" /></td>
          <td>Status : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Version : <label class="inner" /></td>
          <td>Review Preparation Effort : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Size (ekloc) : <label class="inner" /></td>
          <td>Review effort : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Release Date for Review : <label class="inner" /></td>
          <td>Rework effort : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Review Action Taken By : <label class="inner" /></td>
          <td>Review Efficiency : <label class="inner">NaN</label></td>
        </tr>
        <tr class="outer">
          <td>Review Action Taken Date : <label class="inner" /></td>
          <td />
        </tr>
      </table>
      <table>
        <tr class="headerRow">
          <td colspan="2">Review Details</td>
          <td colspan="2">Defect Status Analysis</td>
          <td colspan="2">Defect Type Analysis</td>
          <td colspan="4">Defect Injected Phase Analysis</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td />
          <td />
          <td>Major</td>
          <td>Medium</td>
          <td>Minor</td>
        </tr>
        <tr class="outer">
          <td>Total No of Suggestions</td>
          <td class="inner">0</td>
          <td>Open</td>
          <td class="inner">0</td>
          <td>Logical</td>
          <td class="inner">0</td>
          <td>Initial Project Setup</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td>Total No of Errors</td>
          <td class="inner">0</td>
          <td>On Hold</td>
          <td class="inner">0</td>
          <td>Incomplete</td>
          <td class="inner">0</td>
          <td>Project Initiation</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td>Total</td>
          <td class="inner">0</td>
          <td>Closed</td>
          <td class="inner">0</td>
          <td>UI</td>
          <td class="inner">0</td>
          <td>Requirement Analysis</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td>Rejected</td>
          <td class="inner">0</td>
          <td>Exception Handling</td>
          <td class="inner">0</td>
          <td>Architecture and Design</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td>Documentation</td>
          <td class="inner">0</td>
          <td>Implementation</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td class="inner" />
          <td>QA Testing</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td class="inner" />
          <td>Transition Phase</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td />
          <td class="rAligned">Total</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
      </table>
    </div>
    <br />
    <table class="reviewTable">
      <tr class="headerRow">
        <td>#</td>
        <td>Description</td>
        <td>Status</td>
        <td>DefectType</td>
        <td>InjectedPhase</td>
      </tr>
    </table>
    <div>
      <br />
    Created with <a href="http://visualstudiogallery.msdn.microsoft.com/d1e40c49-da36-42a5-8d5a-4ebe1feabbc9">ReviewPal</a></div>
    <div class="data">
      <Data id="ReviewPalData">
        <CodeReview xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
          <Reviews>
            <Smell>
              <Id>1</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.ResizeCommand.Record.23int position;</HashCode>
              <Severity>Warning</Severity>
              <Weight>23</Weight>
              <Project>DrawingModel</Project>
              <File>ResizeCommand.cs</File>
              <Line>33</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>2</Id>
              <SmellType>Delegate與Event-1</SmellType>
              <HashCode>DelegateAndEvent1.Model._modelChanged._commandManager</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>15</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>3</Id>
              <SmellType>Delegate與Event-1</SmellType>
              <HashCode>DelegateAndEvent1.Model.ModelChangedEventHandler._commandManager</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>16</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>4</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.DrawingModel.Model.253</HashCode>
              <Severity>Warning</Severity>
              <Weight>253</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>12</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>5</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Model.ReleasePointer.28double positionX;double positionY;string shapeType;</HashCode>
              <Severity>Warning</Severity>
              <Weight>28</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>102</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>6</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Model.ReadImageData.21List&lt;string&gt; fileData;</HashCode>
              <Severity>Warning</Severity>
              <Weight>21</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>270</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>7</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Circle.FindPosition.22int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>22</Weight>
              <Project>DrawingModel</Project>
              <File>Circle.cs</File>
              <Line>72</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>8</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Circle.Resize.26int position;int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>26</Weight>
              <Project>DrawingModel</Project>
              <File>Circle.cs</File>
              <Line>95</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>9</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.CreateShape.CreateCircle.double pointerX;double pointerY;double circleWidth;double circleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingModel</Project>
              <File>CreateShape.cs</File>
              <Line>12</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>10</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.CreateShape.CreateRectangle.double pointerX;double pointerY;double rectangleWidth;double rectangleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingModel</Project>
              <File>CreateShape.cs</File>
              <Line>24</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>11</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Frame.FindPosition.22int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>22</Weight>
              <Project>DrawingModel</Project>
              <File>Frame.cs</File>
              <Line>72</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>12</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Frame.Resize.26int position;int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>26</Weight>
              <Project>DrawingModel</Project>
              <File>Frame.cs</File>
              <Line>95</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>13</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.IGraphics.DrawCircle.int circlePositionX;int circlePositionY;int circleWidth;int circleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingModel</Project>
              <File>IGraphics.cs</File>
              <Line>18</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>14</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.IGraphics.DrawRectangle.int rectanglePositionX;int rectanglePositionY;int rectangleWidth;int rectangleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingModel</Project>
              <File>IGraphics.cs</File>
              <Line>21</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>15</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Rectangle.FindPosition.22int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>22</Weight>
              <Project>DrawingModel</Project>
              <File>Rectangle.cs</File>
              <Line>72</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>16</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Rectangle.Resize.26int position;int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>26</Weight>
              <Project>DrawingModel</Project>
              <File>Rectangle.cs</File>
              <Line>95</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>17</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Smile.FindPosition.22int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>22</Weight>
              <Project>DrawingModel</Project>
              <File>Smile.cs</File>
              <Line>88</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>18</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Smile.Resize.27int position;int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>27</Weight>
              <Project>DrawingModel</Project>
              <File>Smile.cs</File>
              <Line>111</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>19</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.ResizeCommand.Record.23int position;</HashCode>
              <Severity>Warning</Severity>
              <Weight>23</Weight>
              <Project>DrawingModel</Project>
              <File>ResizeCommand.cs</File>
              <Line>33</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>20</Id>
              <SmellType>變數-1</SmellType>
              <HashCode>Variable1.GoogleDriveService.SCOPES</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>21</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>21</Id>
              <SmellType>Unsuitable naming(名不符實)-uploadProgressEventHandeler(handeler)</SmellType>
              <HashCode>UnsuitableNaming.GoogleDriveService.UploadFile.uploadProgressEventHandeler</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>145</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>22</Id>
              <SmellType>Unsuitable naming(名不符實)-downloadProgressChangedEventHandeler(handeler)</SmellType>
              <HashCode>UnsuitableNaming.GoogleDriveService.DownloadFile.downloadProgressChangedEventHandeler</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>190</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>23</Id>
              <SmellType>Delegate與Event-1</SmellType>
              <HashCode>DelegateAndEvent1.Model._modelChanged._commandManager</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>15</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>24</Id>
              <SmellType>Delegate與Event-1</SmellType>
              <HashCode>DelegateAndEvent1.Model.ModelChangedEventHandler._commandManager</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>16</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>25</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.DrawingModel.Model.253</HashCode>
              <Severity>Warning</Severity>
              <Weight>253</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>12</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>26</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Model.ReleasePointer.28double positionX;double positionY;string shapeType;</HashCode>
              <Severity>Warning</Severity>
              <Weight>28</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>102</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>27</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Model.ReadImageData.21List&lt;string&gt; fileData;</HashCode>
              <Severity>Warning</Severity>
              <Weight>21</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>270</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>28</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Circle.FindPosition.22int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>22</Weight>
              <Project>DrawingModel</Project>
              <File>Circle.cs</File>
              <Line>72</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>29</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Circle.Resize.26int position;int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>26</Weight>
              <Project>DrawingModel</Project>
              <File>Circle.cs</File>
              <Line>95</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>30</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.CreateShape.CreateCircle.double pointerX;double pointerY;double circleWidth;double circleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingModel</Project>
              <File>CreateShape.cs</File>
              <Line>12</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>31</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.CreateShape.CreateRectangle.double pointerX;double pointerY;double rectangleWidth;double rectangleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingModel</Project>
              <File>CreateShape.cs</File>
              <Line>24</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>32</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Frame.FindPosition.22int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>22</Weight>
              <Project>DrawingModel</Project>
              <File>Frame.cs</File>
              <Line>72</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>33</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Frame.Resize.26int position;int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>26</Weight>
              <Project>DrawingModel</Project>
              <File>Frame.cs</File>
              <Line>95</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>34</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.IGraphics.DrawCircle.int circlePositionX;int circlePositionY;int circleWidth;int circleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingModel</Project>
              <File>IGraphics.cs</File>
              <Line>18</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>35</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.IGraphics.DrawRectangle.int rectanglePositionX;int rectanglePositionY;int rectangleWidth;int rectangleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingModel</Project>
              <File>IGraphics.cs</File>
              <Line>21</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>36</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Rectangle.FindPosition.22int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>22</Weight>
              <Project>DrawingModel</Project>
              <File>Rectangle.cs</File>
              <Line>72</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>37</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Rectangle.Resize.26int position;int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>26</Weight>
              <Project>DrawingModel</Project>
              <File>Rectangle.cs</File>
              <Line>95</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>38</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Smile.FindPosition.22int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>22</Weight>
              <Project>DrawingModel</Project>
              <File>Smile.cs</File>
              <Line>88</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>39</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Smile.Resize.27int position;int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>27</Weight>
              <Project>DrawingModel</Project>
              <File>Smile.cs</File>
              <Line>111</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>40</Id>
              <SmellType>Literal constants(字面常數)-"\\"</SmellType>
              <HashCode>LiteralConstants._projectPath."\\"</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingForm</Project>
              <File>PresentationModel.cs</File>
              <Line>20</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>41</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.WindowsFormsGraphicsAdaptor.DrawCircle.int circlePositionX;int circlePositionY;int circleWidth;int circleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingForm</Project>
              <File>WindowsFormsGraphicsAdaptor.cs</File>
              <Line>51</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>42</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.WindowsFormsGraphicsAdaptor.DrawRectangle.int rectanglePositionX;int rectanglePositionY;int rectangleWidth;int rectangleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingForm</Project>
              <File>WindowsFormsGraphicsAdaptor.cs</File>
              <Line>58</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>43</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.ResizeCommand.Record.23int position;</HashCode>
              <Severity>Warning</Severity>
              <Weight>23</Weight>
              <Project>DrawingModel</Project>
              <File>ResizeCommand.cs</File>
              <Line>33</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>44</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Circle.FindPosition.22int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>22</Weight>
              <Project>DrawingModel</Project>
              <File>Circle.cs</File>
              <Line>72</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>45</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Circle.Resize.26int position;int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>26</Weight>
              <Project>DrawingModel</Project>
              <File>Circle.cs</File>
              <Line>95</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>46</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.CreateShape.CreateCircle.double pointerX;double pointerY;double circleWidth;double circleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingModel</Project>
              <File>CreateShape.cs</File>
              <Line>12</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>47</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.CreateShape.CreateRectangle.double pointerX;double pointerY;double rectangleWidth;double rectangleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingModel</Project>
              <File>CreateShape.cs</File>
              <Line>24</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>48</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Frame.FindPosition.22int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>22</Weight>
              <Project>DrawingModel</Project>
              <File>Frame.cs</File>
              <Line>72</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>49</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Frame.Resize.26int position;int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>26</Weight>
              <Project>DrawingModel</Project>
              <File>Frame.cs</File>
              <Line>95</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>50</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.IGraphics.DrawCircle.int circlePositionX;int circlePositionY;int circleWidth;int circleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingModel</Project>
              <File>IGraphics.cs</File>
              <Line>18</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>51</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.IGraphics.DrawRectangle.int rectanglePositionX;int rectanglePositionY;int rectangleWidth;int rectangleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingModel</Project>
              <File>IGraphics.cs</File>
              <Line>21</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>52</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Rectangle.FindPosition.22int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>22</Weight>
              <Project>DrawingModel</Project>
              <File>Rectangle.cs</File>
              <Line>72</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>53</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Rectangle.Resize.26int position;int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>26</Weight>
              <Project>DrawingModel</Project>
              <File>Rectangle.cs</File>
              <Line>95</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>54</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Smile.FindPosition.22int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>22</Weight>
              <Project>DrawingModel</Project>
              <File>Smile.cs</File>
              <Line>88</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>55</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Smile.Resize.27int position;int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>27</Weight>
              <Project>DrawingModel</Project>
              <File>Smile.cs</File>
              <Line>111</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>56</Id>
              <SmellType>空白與空行-17</SmellType>
              <HashCode>SpacingAndNewLine17.MainPage.xaml.cs.2.        //.        public MainPage()</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>MainPage.xaml.cs</File>
              <Line>38</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>57</Id>
              <SmellType>空白與空行-17</SmellType>
              <HashCode>SpacingAndNewLine17.MainPage.xaml.cs.3.        }.        public void LoadAppBarButtonClick(object sender, RoutedEventArgs e)//載入已存檔案</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>MainPage.xaml.cs</File>
              <Line>88</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>58</Id>
              <SmellType>空白與空行-16</SmellType>
              <HashCode>SpacingAndNewLine16.MainPage.LoadAppBarButtonClick.2</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>MainPage.xaml.cs</File>
              <Line>91</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>59</Id>
              <SmellType>空白與空行-16</SmellType>
              <HashCode>SpacingAndNewLine16.MainPage.DeleteAppBarButtonClick.0</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>MainPage.xaml.cs</File>
              <Line>118</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>60</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.ResizeCommand.Record.23int position;</HashCode>
              <Severity>Warning</Severity>
              <Weight>23</Weight>
              <Project>DrawingModel</Project>
              <File>ResizeCommand.cs</File>
              <Line>33</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>61</Id>
              <SmellType>空白與空行-9</SmellType>
              <HashCode>SpacingAndNewLine9</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>70</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>62</Id>
              <SmellType>空白與空行-9</SmellType>
              <HashCode>SpacingAndNewLine9</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>72</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>63</Id>
              <SmellType>空白與空行-9</SmellType>
              <HashCode>SpacingAndNewLine9</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>167</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>64</Id>
              <SmellType>空白與空行-9</SmellType>
              <HashCode>SpacingAndNewLine9</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>168</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>65</Id>
              <SmellType>Literal constants(字面常數)-2</SmellType>
              <HashCode>LiteralConstants.UploadFile.2</HashCode>
              <Severity>Warning</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>171</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>66</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.GoogleDriveForApp.GoogleDriveForApp.GoogleDriveServiceForApp.237</HashCode>
              <Severity>Warning</Severity>
              <Weight>237</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>20</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>67</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.GoogleDriveServiceForApp.CreateNewService.31string applicationName;string clientSecretFileName;</HashCode>
              <Severity>Red</Severity>
              <Weight>31</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>48</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>68</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.GoogleDriveServiceForApp.ListFileAndFolderWithQueryString.23string queryString;</HashCode>
              <Severity>Warning</Severity>
              <Weight>23</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>126</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>69</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.GoogleDriveServiceForApp.UploadFile.31string uploadFileName;string contentType;Action&lt;IUploadProgress&gt; uploadProgressEventHandler;Action&lt;Google.Apis.Drive.v2.Data.File&gt; responseReceivedEventHandler;</HashCode>
              <Severity>Red</Severity>
              <Weight>31</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>158</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>70</Id>
              <SmellType>函式-2</SmellType>
              <HashCode>Method2.GoogleDriveServiceForApp.SubstractFileName</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>201</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>71</Id>
              <SmellType>Delegate與Event-1</SmellType>
              <HashCode>DelegateAndEvent1.Model._modelChanged._commandManager</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>15</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>72</Id>
              <SmellType>Delegate與Event-1</SmellType>
              <HashCode>DelegateAndEvent1.Model.ModelChangedEventHandler._commandManager</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>16</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>73</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.DrawingModel.Model.253</HashCode>
              <Severity>Warning</Severity>
              <Weight>253</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>12</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>74</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Model.ReleasePointer.28double positionX;double positionY;string shapeType;</HashCode>
              <Severity>Warning</Severity>
              <Weight>28</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>102</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>75</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Model.ReadImageData.21List&lt;string&gt; fileData;</HashCode>
              <Severity>Warning</Severity>
              <Weight>21</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>270</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>76</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Circle.FindPosition.22int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>22</Weight>
              <Project>DrawingModel</Project>
              <File>Circle.cs</File>
              <Line>72</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>77</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Circle.Resize.26int position;int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>26</Weight>
              <Project>DrawingModel</Project>
              <File>Circle.cs</File>
              <Line>95</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>78</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.CreateShape.CreateCircle.double pointerX;double pointerY;double circleWidth;double circleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingModel</Project>
              <File>CreateShape.cs</File>
              <Line>12</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>79</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.CreateShape.CreateRectangle.double pointerX;double pointerY;double rectangleWidth;double rectangleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingModel</Project>
              <File>CreateShape.cs</File>
              <Line>24</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>80</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Frame.FindPosition.22int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>22</Weight>
              <Project>DrawingModel</Project>
              <File>Frame.cs</File>
              <Line>72</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>81</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Frame.Resize.26int position;int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>26</Weight>
              <Project>DrawingModel</Project>
              <File>Frame.cs</File>
              <Line>95</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>82</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.IGraphics.DrawCircle.int circlePositionX;int circlePositionY;int circleWidth;int circleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingModel</Project>
              <File>IGraphics.cs</File>
              <Line>18</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>83</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.IGraphics.DrawRectangle.int rectanglePositionX;int rectanglePositionY;int rectangleWidth;int rectangleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingModel</Project>
              <File>IGraphics.cs</File>
              <Line>21</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>84</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Rectangle.FindPosition.22int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>22</Weight>
              <Project>DrawingModel</Project>
              <File>Rectangle.cs</File>
              <Line>72</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>85</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Rectangle.Resize.26int position;int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>26</Weight>
              <Project>DrawingModel</Project>
              <File>Rectangle.cs</File>
              <Line>95</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>86</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Smile.FindPosition.22int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>22</Weight>
              <Project>DrawingModel</Project>
              <File>Smile.cs</File>
              <Line>88</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>87</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.Smile.Resize.27int position;int positionX;int positionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>27</Weight>
              <Project>DrawingModel</Project>
              <File>Smile.cs</File>
              <Line>111</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>88</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.PresentationModel.SaveImage.23</HashCode>
              <Severity>Warning</Severity>
              <Weight>23</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>PresentationModel.cs</File>
              <Line>104</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>89</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.WindowsStoreGraphicsAdaptor.DrawCircle.int circlePositionX;int circlePositionY;int circleWidth;int circleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>WindowsStoreGraphicsAdaptor.cs</File>
              <Line>45</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>90</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.WindowsStoreGraphicsAdaptor.DrawRectangle.int rectanglePositionX;int rectanglePositionY;int rectangleWidth;int rectangleHeight;RedGreenBlueAlpha redGreenBlueAlpha;</HashCode>
              <Severity>Warning</Severity>
              <Weight>5</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>WindowsStoreGraphicsAdaptor.cs</File>
              <Line>52</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>91</Id>
              <SmellType>變數-2</SmellType>
              <HashCode>Variable2.DrawFrame.Rectangle</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>WindowsStoreGraphicsAdaptor.cs</File>
              <Line>69</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>92</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.WindowsStoreGraphicsAdaptor.CreateArcSegment.29int smilePositionX;int smilePositionY;</HashCode>
              <Severity>Warning</Severity>
              <Weight>29</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>WindowsStoreGraphicsAdaptor.cs</File>
              <Line>75</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>93</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.WindowsStoreGraphicsAdaptor.InitializeShape.Shape shape;int left;int top;int right;int bottom;SolidColorBrush fillColorBrush;</HashCode>
              <Severity>Red</Severity>
              <Weight>6</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>WindowsStoreGraphicsAdaptor.cs</File>
              <Line>105</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>94</Id>
              <SmellType>Long parameter list(過長參數列)</SmellType>
              <HashCode>LongParameterList.WindowsStoreGraphicsAdaptor.InitializeFrame.Shape shape;int left;int top;int right;int bottom;SolidColorBrush fillColorBrush;</HashCode>
              <Severity>Red</Severity>
              <Weight>6</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>WindowsStoreGraphicsAdaptor.cs</File>
              <Line>114</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>95</Id>
              <SmellType>變數-1</SmellType>
              <HashCode>Variable1.App.transitions</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Shared</Project>
              <File>App.xaml.cs</File>
              <Line>29</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>96</Id>
              <SmellType>Unresolved warnings(忽視警告)-All projects referencing DrawingModel.csproj must install nuget package Microsoft.Bcl.Build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317569.</SmellType>
              <HashCode>UnitTestProject\UnitTestProject..Unresolved warnings(忽視警告)-All projects referencing DrawingModel.csproj must install nuget package Microsoft.Bcl.Build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317569..1</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>UnitTestProject\UnitTestProject</Project>
              <Line>1</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>97</Id>
              <SmellType>Unresolved warnings(忽視警告)-'DrawingModel.Model.Model()' 的保護層級導致無法對其進行存取</SmellType>
              <HashCode>UnitTestProject\UnitTestProject.UnitTest1.cs.Unresolved warnings(忽視警告)-'DrawingModel.Model.Model()' 的保護層級導致無法對其進行存取.11</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>UnitTestProject\UnitTestProject</Project>
              <File>UnitTest1.cs</File>
              <Line>11</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>98</Id>
              <SmellType>Unresolved warnings(忽視警告)-'DrawingModel.Model.Model()' 的保護層級導致無法對其進行存取</SmellType>
              <HashCode>UnitTestProject\UnitTestProject.UnitTest1.cs.Unresolved warnings(忽視警告)-'DrawingModel.Model.Model()' 的保護層級導致無法對其進行存取.21</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>UnitTestProject\UnitTestProject</Project>
              <File>UnitTest1.cs</File>
              <Line>21</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
          </Reviews>
          <HashCodeIgnoreList />
          <AnalysisFileManager>
            <AnalysisFiles>
              <AnalysisFile>
                <RelativePath>command\ChangeColorCommand.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>command\ClearCommand.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>command\CommandManager.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>command\DeleteCommand.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>command\DrawCommand.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>command\ICommand.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>command\MoveCommand.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>command\ResizeCommand.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Model.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\AssemblyInfo.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Shape\Circle.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Shape\CreateShape.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Shape\Frame.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Shape\IGraphics.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Shape\Points.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Shape\Rectangle.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Shape\RGBA.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Shape\ShapeType.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Shape\Smile.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Form1.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>ViewOrController</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Form1.Designer.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\command\ChangeColorCommand.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\command\ClearCommand.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\command\CommandManager.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\command\DeleteCommand.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\command\DrawCommand.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\command\ICommand.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\command\MoveCommand.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\command\ResizeCommand.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Model\GoogleDriveService.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Model.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\Circle.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\CreateShape.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\Frame.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\IGraphics.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\Points.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\Rectangle.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\RGBA.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\ShapeType.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\Smile.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PresentationModel\DoubleBufferedPanel.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PresentationModel\PresentationModel.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PresentationModel\WindowsFormsGraphicsAdaptor.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Program.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\AssemblyInfo.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\Resources.Designer.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\Settings.Designer.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\command\ChangeColorCommand.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\command\ClearCommand.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\command\CommandManager.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\command\DeleteCommand.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\command\DrawCommand.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\command\ICommand.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\command\MoveCommand.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\command\ResizeCommand.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\Circle.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\CreateShape.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\Frame.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\IGraphics.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\Points.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\Rectangle.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\RGBA.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\ShapeType.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Shape\Smile.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\AssemblyInfo.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>UnitTest1.cs</RelativePath>
                <ProjectName>UnitTestProject</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>App.xaml.cs</RelativePath>
                <ProjectName>DrawingApp.Shared</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingApp.Shared\App.xaml.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>MainPage.xaml.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\command\ChangeColorCommand.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\command\ClearCommand.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\command\CommandManager.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\command\DeleteCommand.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\command\DrawCommand.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\command\ICommand.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\command\MoveCommand.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\command\ResizeCommand.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Model\GoogleDriveServiceForApp.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\Model.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\Shape\Circle.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\Shape\CreateShape.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\Shape\Frame.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\Shape\IGraphics.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\Shape\Points.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\Shape\Rectangle.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\Shape\RGBA.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\Shape\ShapeType.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\Shape\Smile.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PresentationModel\PresentationModel.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PresentationModel\WindowsStoreGraphicsAdaptor.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\AssemblyInfo.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingApp.Shared\App.xaml.cs</RelativePath>
                <ProjectName>DrawingApp.WindowsPhone</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>MainPage.xaml.cs</RelativePath>
                <ProjectName>DrawingApp.WindowsPhone</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\AssemblyInfo.cs</RelativePath>
                <ProjectName>DrawingApp.WindowsPhone</ProjectName>
                <AnalysisFileType>Unknown</AnalysisFileType>
              </AnalysisFile>
            </AnalysisFiles>
          </AnalysisFileManager>
          <TotalLine>7249</TotalLine>
        </CodeReview>
      </Data>
    </div>
  </body>
</html>